import { createContext, useState, useContext } from 'react';
const translations = {
  en: {
    // Navbar
    Home: "Home",
    AccessPortal: "Access Portal",
    About: "About",
    Contact: "Contact",
    Login: "Login",
    Register: "Register",
    
    // Auth
    loginTitle: "Login to CrowdCivic",
    registerTitle: "Citizen Registration",
    mobileNumber: "Mobile Number",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    wardNumber: "Ward Number",
    area: "Location / Area",
    district: "District",
    loginBtn: "Login",
    registerBtn: "Register",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    selectWard: "Select Ward",
    selectArea: "Select Area",
    dindigul: "Dindigul",
    citizenPortal: "Citizen Portal",
    adminPortal: "Admin Portal",
    portalSelection: "Portal Selection",
    selectRole: "Please select your portal to continue",
    backToPortals: "Back to Portals",
    enterCredentials: "Enter your credentials to access the system",
    
    // Landing Page
    heroSubtitle: "AI-Powered Smart City Initiative",
    heroTitle: "CrowdCivic",
    heroDesc: "Tamil Nadu's premier smart governance platform. Report civic issues, track real-time resolution, and help build a smarter, safer Dindigul together.",
    aiDetection: "AI Detection",
    aiDesc: "Auto-detect duplicates and prioritize critical civic issues.",
    realTime: "Real-time Tracking",
    realTimeDesc: "Track your complaint status from submission to resolution.",
    smartAnalytics: "Smart Analytics",
    smartAnalyticsDesc: "Municipality dashboard with heatmaps and performance metrics.",
    communityDriven: "Community Driven",
    communityDrivenDesc: "Dindigul citizens working together for a better city.",
    liveActivity: "Live Civic Activity Feed",
    liveActivityDesc: "Real-time transparency on issues being reported and resolved across Dindigul municipality.",
    resolvedThisWeek: "Issues Resolved This Week",
    justNow: "Just now",
    realTimeTag: "Real-time",
    buildSmarterTitle: "Build a Smarter Dindigul",
    buildSmarterDesc: "Join thousands of citizens making Dindigul a better place. Report issues, share feedback, and track our progress.",
    registerNow: "Register Now",
    learnMore: "Learn More",
    issueResolved: "Issue Resolved",
    newReport: "New Report",
    
    // About & Contact
    aboutTitle: "About CrowdCivic",
    aboutSubtitle: "An MCA final year project bridging the gap between citizens and municipal authorities through modern technology.",
    problemTitle: "The Problem",
    problemDesc1: "Traditional civic reporting systems are often slow, paper-based, and lack transparency. Citizens find it difficult to track the status of their complaints, leading to frustration and a lack of trust in municipal authorities.",
    problemDesc2: "Furthermore, authorities struggle to prioritize and manage issues efficiently without a centralized, data-driven platform.",
    solutionTitle: "Our Solution",
    solutionDesc1: "CrowdCivic provides a centralized, web-based platform where citizens can easily report issues with photos and precise locations.",
    solutionDesc2: "Municipal authorities receive an organized dashboard to track, assign, and resolve these issues efficiently, providing real-time updates back to the citizens.",
    highlightsTitle: "Project Highlights",
    objective: "Objective",
    objectiveDesc: "Streamline civic management and enhance citizen engagement.",
    techStack: "Tech Stack",
    techStackDesc: "React, Tailwind CSS, Framer Motion, Recharts.",
    targetAudience: "Target Audience",
    targetAudienceDesc: "Local citizens and municipal administrative bodies.",
    innovation: "Innovation",
    innovationDesc: "Real-time tracking, intuitive UI, and data analytics.",
    contactTitle: "Get in Touch",
    contactSubtitle: "Have questions or suggestions? We'd love to hear from you.",
    phone: "Phone",
    sendMessage: "Send Message",
    messageSent: "Message sent successfully!",
    
    // Citizen Dashboard
    totalReports: "Total Reports",
    totalComplaints: "Total Complaints",
    awaitingVerification: "Awaiting Verification",
    pending: "Pending",
    inProgress: "In Progress",
    resolved: "Resolved",
    reportIssue: "Report an Issue",
    issueTitle: "Issue Title",
    category: "Category",
    location: "Location",
    submitReport: "Submit Report",
    weeklyTrend: "Weekly Reporting Trend",
    liveMap: "Live Dindigul Node Map",
    dashboard: "Dashboard",
    myReports: "My Complaints",
    manageYourComplaints: "Manage and track your reported civic issues",
    settings: "Settings",
    detailedDesc: "Detailed Description",
    descPlaceholder: "Describe the issue in detail...",
    similarIssue: "Similar Issue Nearby!",
    matchFound: "Our smart detection system found a match with an existing unresolved report.",
    supportExisting: "Support Existing Report",
    reportAnyway: "I Want to Report Mine Anyway",
    
    // Admin Sections
    controlCenter: "Control Center",
    allComplaints: "All Complaints",
    activityLogs: "Activity Logs",
    management: "Management",
    analytics: "Analytics",
    wardPerformance: "Ward-wise Performance",
    deptPerformance: "Department Performance",
    issueDensity: "Issue Density Heatmap",
    systemLogs: "System Audit Logs",
    notifications: "Notifications",
    notificationFeed: "Live Notification Feed",
    recentAlerts: "Recent Alerts",
    heatmapSummary: "Complaint Heatmap Summary",
    monitoring: "Municipal Monitoring Dashboard",
    mgmtCenter: "Complaint Management Center",
    systemAudit: "System Audit & History",
    
    // Table & Workflow
    tokenID: "Token ID",
    citizenName: "Citizen Name",
    submissionDate: "Submission Date",
    actions: "Actions",
    viewDetails: "View Details",
    assignWorker: "Assign Worker",
    uploadProof: "Upload Resolution Photo",
    beforePhoto: "Before Photo",
    afterPhoto: "After Photo",
    completionNotes: "Resolution Notes",
    submitVerification: "Submit for Verification",
    workProof: "Work Proof",
    reworkRequested: "Citizen requested rework",
    
    // Logs & Filters
    filterDate: "Date Filter",
    filterUser: "User Filter",
    filterAdmin: "Admin Filter",
    activitySearch: "Search Activities...",
    
    // General
    searchPlaceholder: "Filter ID or Title...",
    allStatus: "All Status",
    complaint: "Complaint",
    Status: "Status",
    Pending: "Pending",
    "In Progress": "In Progress",
    Submitted: "Submitted",
    Assigned: "Assigned",
    "Work In Progress": "Work In Progress",
    "Awaiting Citizen Confirmation": "Awaiting Verification",
    Resolved: "Resolved",
    Rejected: "Rejected",
    Reopened: "Reopened",
    total: "Total",
    new: "New",
    active: "Active",
    done: "Done",
    systemMaintenance: "System Maintenance at 02:00 AM",
    newAdminRequest: "New admin account requested",
    ward15Surge: "High report surge in Ward 15",
    auditLog: "View Full Audit Log",
    categoryAnalytics: "Issue Category Analytics",
    locationPlaceholder: "Search location in Dindigul...",
    assignedWorker: "Assigned Worker"
  },
  ta: {
    // Navbar
    Home: "முகப்பு",
    AccessPortal: "அணுகல் மையம்",
    About: "பற்றி",
    Contact: "தொடர்புக்கு",
    Login: "உள்நுழை",
    Register: "பதிவு செய்க",
    
    // Auth
    loginTitle: "க்ரவுட்சிலிக்-ல் உள்நுழையவும்",
    registerTitle: "குடிமக்கள் பதிவு",
    mobileNumber: "மொபைல் எண்",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    name: "முழுப் பெயர்",
    wardNumber: "வார்டு எண்",
    area: "இருப்பிடம் / பகுதி",
    district: "மாவட்டம்",
    loginBtn: "உள்நுழைய",
    registerBtn: "பதிவு செய்",
    noAccount: "கணக்கு இல்லையா?",
    haveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    selectWard: "வார்டை தேர்ந்தெடுக்கவும்",
    selectArea: "பகுதியை தேர்ந்தெடுக்கவும்",
    dindigul: "திண்டுக்கல்",
    citizenPortal: "குடிமக்கள் தளம்",
    adminPortal: "நிர்வாக தளம்",
    portalSelection: "தள தேர்வு",
    selectRole: "தொடர உங்கள் தளத்தைத் தேர்ந்தெடுக்கவும்",
    backToPortals: "தளங்களுக்குத் திரும்பு",
    enterCredentials: "கணினியை அணுக உங்கள் விவரங்களை உள்ளிடவும்",
    
    // Landing Page
    heroSubtitle: "AI-ஆல் இயங்கும் ஸ்மார்ட் சிட்டி முயற்சி",
    heroTitle: "க்ரவுட்சிலிக்",
    heroDesc: "தமிழ்நாட்டின் முதன்மையான ஸ்மார்ட் கவர்னன்ஸ் தளம். பொது புகார்களைப் பதிவு செய்யுங்கள், நிகழ்நேரத் தீர்வைக் கண்காணியுங்கள், மேலும் சிறந்த, பாதுகாப்பான திண்டுக்கல்லை இணைந்து உருவாக்குவோம்.",
    aiDetection: "AI கண்டறிதல்",
    aiDesc: "ஒரே மாதிரியான புகார்களை தானாகக் கண்டறிந்து முக்கியமான பிரச்சனைகளுக்கு முன்னுரிமை அளிக்கிறது.",
    realTime: "நிகழ்நேர கண்காணிப்பு",
    realTimeDesc: "உங்கள் புகாரின் நிலையைச் சமர்ப்பித்தது முதல் தீர்வு வரை கண்காணியுங்கள்.",
    smartAnalytics: "ஸ்மார்ட் பகுப்பாய்வு",
    smartAnalyticsDesc: "ஹீட்மேப்கள் மற்றும் செயல்திறன் அளவீடுகளுடன் கூடிய நகராட்சி டாஷ்போர்டு.",
    communityDriven: "சமூக உந்துதல்",
    communityDrivenDesc: "சிறந்த நகரத்திற்காக திண்டுக்கல் குடிமக்கள் இணைந்து செயல்படுகிறார்கள்.",
    liveActivity: "நேரலை செயல்பாட்டு ஓட்டம்",
    liveActivityDesc: "திண்டுக்கல் நகராட்சி முழுவதும் புகாரளிக்கப்படும் மற்றும் தீர்க்கப்படும் பிரச்சனைகளின் நிகழ்நேரத் தகவல்கள்.",
    resolvedThisWeek: "இந்த வாரம் தீர்க்கப்பட்ட புகார்கள்",
    justNow: "இப்போது",
    realTimeTag: "நிகழ்நேரம்",
    buildSmarterTitle: "சிறந்த திண்டுக்கல்லை உருவாக்குவோம்",
    buildSmarterDesc: "திண்டுக்கல்லை சிறந்த இடமாக மாற்றும் ஆயிரக்கணக்கான குடிமக்கள் இணைந்து புகாரளிக்கவும், கருத்துக்களைப் பகிரவும், எங்கள் முன்னேற்றத்தைக் கண்காணியுங்கள்.",
    registerNow: "இப்போது பதிவு செய்க",
    learnMore: "மேலும் அறிக",
    issueResolved: "புகார் தீர்க்கப்பட்டது",
    newReport: "புதிய புகார்",

    // About & Contact
    aboutTitle: "க்ரவுட்சிலிக் பற்றி",
    aboutSubtitle: "நவீன தொழில்நுட்பத்தின் மூலம் குடிமக்களுக்கும் நகராட்சி அதிகாரிகளுக்கும் இடையிலான இடைவெளியைக் குறைக்கும் ஒரு MCA இறுதியாண்டு திட்டம்.",
    problemTitle: "பிரச்சனை",
    problemDesc1: "பாரம்பரிய குடிமைப் புகார் அமைப்புகள் பெரும்பாலும் மெதுவானவை, காகிதம் சார்ந்தவை மற்றும் வெளிப்படைத்தன்மை அற்றவை. குடிமக்கள் தங்கள் புகார்களின் நிலையைத் தொடர்ந்து கண்காணிப்பது கடினம்.",
    problemDesc2: "மேலும், ஒரு மையப்படுத்தப்பட்ட, தரவு சார்ந்த தளம் இல்லாமல் பிரச்சனைகளை முன்னுரிமைப்படுத்துவதற்கும் நிர்வகிப்பதற்கும் அதிகாரிகள் சிரமப்படுகிறார்கள்.",
    solutionTitle: "எங்கள் தீர்வு",
    solutionDesc1: "க்ரவுட்சிலிக் ஒரு மையப்படுத்தப்பட்ட, வலை-சார்ந்த தளத்தை வழங்குகிறது, அங்கு குடிமக்கள் புகைப்படங்கள் மற்றும் துல்லியமான இடங்களுடன் பிரச்சனைகளை எளிதாகப் புகாரளிக்கலாம்.",
    solutionDesc2: "நகராட்சி அதிகாரிகள் புகார்களைத் திறமையாகக் கண்காணிக்கவும், ஒதுக்கவும் மற்றும் தீர்க்கவும் ஒரு ஒழுங்கமைக்கப்பட்ட டாஷ்போர்டைப் பெறுகிறார்கள்.",
    highlightsTitle: "திட்டத்தின் சிறப்பம்சங்கள்",
    objective: "நோக்கம்",
    objectiveDesc: "குடிமை நிர்வாகத்தை நெறிப்படுத்துதல் மற்றும் குடிமக்களின் ஈடுபாட்டை மேம்படுத்துதல்.",
    techStack: "தொழில்நுட்பங்கள்",
    techStackDesc: "React, Tailwind CSS, Framer Motion, Recharts.",
    targetAudience: "இலக்கு பார்வையாளர்கள்",
    targetAudienceDesc: "உள்ளூர் குடிமக்கள் மற்றும் நகராட்சி நிர்வாக அமைப்புகள்.",
    innovation: "புதுமை",
    innovationDesc: "நிகழ்நேர கண்காணிப்பு, எளிமையான இடைமுகம் மற்றும் தரவு பகுப்பாய்வு.",
    contactTitle: "தொடர்பு கொள்ள",
    contactSubtitle: "கேள்விகள் அல்லது ஆலோசனைகள் உள்ளதா? உங்களிடமிருந்து கேட்க விரும்புகிறோம்.",
    phone: "தொலைபேசி",
    sendMessage: "செய்தி அனுப்பு",
    messageSent: "செய்தி வெற்றிகரமாக அனுப்பப்பட்டது!",

    // Citizen Dashboard
    totalReports: "மொத்த புகார்கள்",
    totalComplaints: "மொத்த புகார்கள்",
    awaitingVerification: "சரிபார்ப்பிற்காக",
    pending: "நிலுவையில்",
    inProgress: "நடவடிக்கையில்",
    resolved: "தீர்க்கப்பட்டது",
    reportIssue: "புகாரை பதிவு செய்",
    issueTitle: "புகார் தலைப்பு",
    category: "வகை",
    location: "இடம்",
    submitReport: "சமர்ப்பி",
    weeklyTrend: "வாராந்திர போக்கு",
    liveMap: "நேரலை வரைபடம்",
    dashboard: "டாஷ்போர்டு",
    myReports: "எனது புகார்கள்",
    manageYourComplaints: "உங்கள் புகார்களை மேலாண்மை செய்து கண்காணியுங்கள்",
    settings: "அமைப்புகள்",
    detailedDesc: "விரிவான விளக்கம்",
    descPlaceholder: "பிரச்சனையை விரிவாக விவரிக்கவும்...",
    similarIssue: "அருகில் இதே போன்ற பிரச்சனை உள்ளது!",
    matchFound: "எங்கள் ஸ்மார்ட் சிஸ்டம் தற்போதுள்ள ஒரு புகாருடன் ஒத்துப்போவதைக் கண்டறிந்துள்ளது.",
    supportExisting: "தற்போதுள்ள புகாரை ஆதரிக்கவும்",
    reportAnyway: "எனது புகாரை தனியாகப் பதிவு செய்ய விரும்புகிறேன்",
    
    // Admin Sections
    controlCenter: "கட்டுப்பாட்டு மையம்",
    allComplaints: "அனைத்து புகார்கள்",
    activityLogs: "கணினி பதிவுகள்",
    management: "நிர்வாகம்",
    analytics: "பகுப்பாய்வு",
    wardPerformance: "வார்டு வாரியான செயல்பாடு",
    deptPerformance: "துறை வாரியான செயல்பாடு",
    issueDensity: "புகார் அடர்த்தி",
    systemLogs: "கணினி தணிக்கை பதிவுகள்",
    notifications: "அறிவிப்புகள்",
    notificationFeed: "நிகழ்நேர அறிவிப்புகள்",
    recentAlerts: "சமீபத்திய எச்சரிக்கைகள்",
    heatmapSummary: "புகார் அடர்த்தி வரைபடம்",
    monitoring: "நகராட்சி கண்காணிப்பு டாஷ்போர்டு",
    mgmtCenter: "புகார் மேலாண்மை மையம்",
    systemAudit: "கணினி தணிக்கை மற்றும் வரலாறு",
    
    // Table & Workflow
    tokenID: "அடையாள எண்",
    citizenName: "குடிமகன் பெயர்",
    submissionDate: "சமர்ப்பிக்கப்பட்ட தேதி",
    actions: "செயல்கள்",
    viewDetails: "விவரங்களைக் காண்க",
    assignWorker: "ஊழியரை ஒதுக்கு",
    uploadProof: "தீர்வுப் புகைப்படத்தை பதிவேற்று",
    beforePhoto: "முந்தைய புகைப்படம்",
    afterPhoto: "பிந்தைய புகைப்படம்",
    completionNotes: "தீர்வு குறிப்புகள்",
    submitVerification: "சரிபார்ப்பிற்கு சமர்ப்பி",
    workProof: "பணி நிறைவு சான்று",
    reworkRequested: "குடிமகன் மறுவேலை கோரியுள்ளார்",
    
    // Logs & Filters
    filterDate: "தேதி வடிகட்டி",
    filterUser: "பயனர் வடிகட்டி",
    filterAdmin: "நிர்வாகி வடிகட்டி",
    activitySearch: "நடவடிக்கைகளைத் தேடுக...",
    
    // General
    searchPlaceholder: "ஐடி அல்லது தலைப்பு மூலம் தேடுக...",
    allStatus: "அனைத்து நிலைகளும்",
    complaint: "புகார்",
    Status: "நிலை",
    Pending: "நிலுவையில்",
    "In Progress": "நடவடிக்கையில்",
    Submitted: "சமர்ப்பிக்கப்பட்டது",
    Assigned: "ஒதுக்கப்பட்டது",
    "Work In Progress": "நடவடிக்கையில் உள்ளது",
    "Awaiting Citizen Confirmation": "சரிபார்ப்பிற்காக",
    Resolved: "தீர்க்கப்பட்டது",
    Rejected: "நிராகரிக்கப்பட்டது",
    Reopened: "மீண்டும் திறக்கப்பட்டது",
    total: "மொத்தம்",
    new: "புதியது",
    active: "செயலில்",
    done: "முடிந்தது",
    systemMaintenance: "காலை 02:00 மணிக்கு கணினி பராமரிப்பு",
    newAdminRequest: "புதிய நிர்வாகக் கணக்கு கோரப்பட்டது",
    ward15Surge: "வார்டு 15-ல் புகார்கள் அதிகரிப்பு",
    auditLog: "முழு தணிக்கை பதிவைக் காண்க",
    categoryAnalytics: "பிரச்சனை வகை பகுப்பாய்வு",
    locationPlaceholder: "திண்டுக்கல்லில் இருப்பிடத்தைத் தேடுக...",
    assignedWorker: "ஒதுக்கப்பட்ட ஊழியர்"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('crowdcivic_lang') || 'ta';
  });

  const toggleLanguage = () => {
    const newLang = language === 'ta' ? 'en' : 'ta';
    setLanguage(newLang);
    localStorage.setItem('crowdcivic_lang', newLang);
  };

  const t = (key) => {
    if (!translations[language][key]) {
        console.warn(`Translation key missing: ${key}`);
        return key;
    }
    return translations[language][key];
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
